artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/98eb1fe0e5c44ab6857239a1b91d248f/artifacts
end_time: 1763301631557
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 98eb1fe0e5c44ab6857239a1b91d248f
run_name: Logistic Regression_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763301631303
status: 3
tags: []
user_id: Ankuc
