artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/b1d66cba24f54026a51c273eb0b5fe9c/artifacts
end_time: 1763256077870
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: b1d66cba24f54026a51c273eb0b5fe9c
run_name: XGB_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763255197264
status: 3
tags: []
user_id: Ankuc
