artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/555ac968919343e8afbaef8b4cab06b5/artifacts
end_time: 1763306395757
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 555ac968919343e8afbaef8b4cab06b5
run_name: Logistic Regression_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763306395511
status: 3
tags: []
user_id: Ankuc
