artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/1f60464ac6a8495ea2a33b4ab40ad2f3/artifacts
end_time: 1763257860173
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 1f60464ac6a8495ea2a33b4ab40ad2f3
run_name: Logistic Regression_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763257859815
status: 3
tags: []
user_id: Ankuc
