artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/8bfbc990473f4016b9ff516dddfc5736/artifacts
end_time: 1763258275361
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 8bfbc990473f4016b9ff516dddfc5736
run_name: Random Forest_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763258226966
status: 3
tags: []
user_id: Ankuc
