artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/fc9c368ff8fc47f183eabf1981045dc0/artifacts
end_time: 1763312296029
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: fc9c368ff8fc47f183eabf1981045dc0
run_name: Logistic Regression_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763312295669
status: 3
tags: []
user_id: Ankuc
