artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/79772f7fa99a4fae9af331cc64a71a87/artifacts
end_time: 1763257669148
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 79772f7fa99a4fae9af331cc64a71a87
run_name: Random Forest_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763257457457
status: 3
tags: []
user_id: Ankuc
