artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/6a77edd1c81844eab263c03577ff67de/artifacts
end_time: 1763308970373
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 6a77edd1c81844eab263c03577ff67de
run_name: Model_Training_Pipeline
source_name: ''
source_type: 4
source_version: ''
start_time: 1763308717561
status: 3
tags: []
user_id: Ankuc
