artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/6b9740dcb03c40d0abac2692b96dda27/artifacts
end_time: 1763301631295
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 6b9740dcb03c40d0abac2692b96dda27
run_name: XGB_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763301390263
status: 3
tags: []
user_id: Ankuc
