artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/c23ea2870cd24a85bc63d0d40ddd92b2/artifacts
end_time: 1763304727137
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: c23ea2870cd24a85bc63d0d40ddd92b2
run_name: Model_Training_Pipeline
source_name: ''
source_type: 4
source_version: ''
start_time: 1763304381132
status: 3
tags: []
user_id: Ankuc
