artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/7020a2b02fdd4fbfb17eef4ee7a4835b/artifacts
end_time: 1763255197255
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 7020a2b02fdd4fbfb17eef4ee7a4835b
run_name: Random Forest_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763254873683
status: 3
tags: []
user_id: Ankuc
