artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/d38b33ab1b89470d8acaf9bbab2c41c4/artifacts
end_time: 1763309610013
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: d38b33ab1b89470d8acaf9bbab2c41c4
run_name: Logistic Regression_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763309609673
status: 3
tags: []
user_id: Ankuc
