artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/ae6bf7efa5f946eba339fa7553aa2efa/artifacts
end_time: 1763315977700
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: ae6bf7efa5f946eba339fa7553aa2efa
run_name: Logistic Regression_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763315977370
status: 3
tags: []
user_id: Ankuc
