artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/ae687f18617e4adf937e1ade6a5d7fcd/artifacts
end_time: 1763315983725
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: ae687f18617e4adf937e1ade6a5d7fcd
run_name: Model_Training_Pipeline
source_name: ''
source_type: 4
source_version: ''
start_time: 1763315786555
status: 3
tags: []
user_id: Ankuc
