aliases:
  Production: '2'
  Staging: '10'
creation_timestamp: 1763304727038
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1763315984085
name: Titanic_predictor_Random Forest
