artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/0cd8829735f74551b94671cb30afd0cd/artifacts
end_time: 1763304706698
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 0cd8829735f74551b94671cb30afd0cd
run_name: Logistic Regression_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763304705078
status: 3
tags: []
user_id: Ankuc
