artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/370c78b344ae4ae6b7536cfa115c2bca/artifacts
end_time: 1763304705003
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 370c78b344ae4ae6b7536cfa115c2bca
run_name: XGB_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763304529705
status: 3
tags: []
user_id: Ankuc
