artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/32d4beb6a83349eba2dbedbcf3b2d31d/artifacts
end_time: 1763747886959
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 32d4beb6a83349eba2dbedbcf3b2d31d
run_name: Training_Run
source_name: ''
source_type: 4
source_version: ''
start_time: 1763747732928
status: 3
tags: []
user_id: Ankuc
