artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/3a8d1a46d3d64ebca64d3de8e4344073/artifacts
end_time: 1763306259704
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 3a8d1a46d3d64ebca64d3de8e4344073
run_name: Random Forest_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763306099295
status: 3
tags: []
user_id: Ankuc
