creation_timestamp: 1763306400910
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1763306400910
model_id: m-ee2b0e49c43c482ca32e050175dc7fde
name: Titanic_predictor_XGB
run_id: d56f7947ab3742a181d90a8c1b87cd07
run_link: null
source: models:/m-ee2b0e49c43c482ca32e050175dc7fde
status: READY
status_message: null
storage_location: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/models/m-ee2b0e49c43c482ca32e050175dc7fde/artifacts
user_id: null
version: 2
