creation_timestamp: 1763315983562
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1763315983562
model_id: m-9091cc44067c464db71fca481f926f19
name: Titanic_predictor_Random Forest
run_id: ae687f18617e4adf937e1ade6a5d7fcd
run_link: null
source: models:/m-9091cc44067c464db71fca481f926f19
status: READY
status_message: null
storage_location: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/models/m-9091cc44067c464db71fca481f926f19/artifacts
user_id: null
version: 10
