artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/d8a3e68fb5f84973a2a874ccae96cd13/artifacts
end_time: 1763258792888
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: d8a3e68fb5f84973a2a874ccae96cd13
run_name: Model_Training_Pipeline
source_name: ''
source_type: 4
source_version: ''
start_time: 1763258394690
status: 4
tags: []
user_id: Ankuc
