artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/eb785b6eb72b4d7587eb17e2dad30a8a/artifacts
end_time: 1763258132429
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: eb785b6eb72b4d7587eb17e2dad30a8a
run_name: Logistic Regression_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763258132168
status: 3
tags: []
user_id: Ankuc
