artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/36250a8efd4a4b89b63b4fed47d36e84/artifacts
end_time: 1763254591552
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 36250a8efd4a4b89b63b4fed47d36e84
run_name: Model_Training_Pipeline
source_name: ''
source_type: 4
source_version: ''
start_time: 1763253370680
status: 4
tags: []
user_id: Ankuc
