artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/bd1a548aa4ec4114b12c8d833db887c3/artifacts
end_time: 1763308005640
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: bd1a548aa4ec4114b12c8d833db887c3
run_name: Logistic Regression_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763308005040
status: 3
tags: []
user_id: Ankuc
