artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/9cefbbb6f3e5426f88fd9327559cc98f/artifacts
end_time: 1763312724638
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 9cefbbb6f3e5426f88fd9327559cc98f
run_name: Random Forest_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763312621612
status: 3
tags: []
user_id: Ankuc
