artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/bcb5840a369c4a6f9cca6b72197ffc13/artifacts
end_time: 1763311911544
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: bcb5840a369c4a6f9cca6b72197ffc13
run_name: Logistic Regression_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763311909656
status: 3
tags: []
user_id: Ankuc
