aliases:
  Production: '1'
  Staging: '2'
creation_timestamp: 1763739697541
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1763747888159
name: Titanic_predictor_Random_Forest
