artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/c603309c442c4bd192ccbfa2f10020bd/artifacts
end_time: 1763747747261
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: c603309c442c4bd192ccbfa2f10020bd
run_name: Random Forest_opt
source_name: ''
source_type: 4
source_version: ''
start_time: 1763747733832
status: 3
tags: []
user_id: Ankuc
