artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/31da206c1ff14525abbaefcb47d77eb1/artifacts
end_time: 1763258984468
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 31da206c1ff14525abbaefcb47d77eb1
run_name: Random Forest_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763258929583
status: 3
tags: []
user_id: Ankuc
