artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/4fedd793b9754650b2ff1d22cc2131be/artifacts
end_time: 1763311101464
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 4fedd793b9754650b2ff1d22cc2131be
run_name: XGB_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763310843323
status: 3
tags: []
user_id: Ankuc
