artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/2a5b9dbcfd85416fbb147e5c98224790/artifacts
end_time: 1763311102332
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 2a5b9dbcfd85416fbb147e5c98224790
run_name: Logistic Regression_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763311101488
status: 3
tags: []
user_id: Ankuc
