artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/b8eb30a7c67744e182623fd79886cbcb/artifacts
end_time: 1763304529696
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: b8eb30a7c67744e182623fd79886cbcb
run_name: Random Forest_Optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1763304381435
status: 3
tags: []
user_id: Ankuc
