artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/acc7547e13ee4c1e8009f231d5464fb4/artifacts
end_time: 1763301631994
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: acc7547e13ee4c1e8009f231d5464fb4
run_name: Model_Training_Pipeline
source_name: ''
source_type: 4
source_version: ''
start_time: 1763301178232
status: 4
tags: []
user_id: Ankuc
