aliases:
  Production: '4'
  Staging: '4'
creation_timestamp: 1763302270604
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1763315441437
name: Titanic_predictor_XGB
