artifact_uri: file:C:/Users/Ankuc/OneDrive/Desktop/Titanic/mlrun/236988911479320639/59fe434316ec4d6e8b1cf939eb9d2a92/artifacts
end_time: 1763258132434
entry_point_name: ''
experiment_id: '236988911479320639'
lifecycle_stage: active
run_id: 59fe434316ec4d6e8b1cf939eb9d2a92
run_name: Model_Training_Pipeline
source_name: ''
source_type: 4
source_version: ''
start_time: 1763258030733
status: 4
tags: []
user_id: Ankuc
